name: 24-game
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.9
  - pip
  # Frontend dependencies (available via conda)
  - kivy
  # Backend/Database dependencies (available via conda)
  - sqlite
  - postgresql
  # Development and testing tools
  - pytest
  - black
  - isort
  - flake8
  - pip:
    # Frontend dependencies (pip-only)
    - kivy>=2.1.0
    - kivymd>=1.1.1
    - fastapi>=0.104.0
    - uvicorn[standard]>=0.24.0
    - sqlalchemy>=2.0.0
    - asyncpg>=0.29.0
    - psycopg2-binary>=2.9.0
    - python-multipart>=0.0.6
    - pydantic>=2.0.0
    - pydantic-settings>=2.0.0
    - python-jose[cryptography]>=3.3.0
    - passlib[bcrypt]>=1.7.4
    - cryptography>=41.0.0
    # Testing dependencies
    - pytest>=7.4.0
    - pytest-asyncio>=0.21.0
    - httpx>=0.25.0
    - requests>=2.31.0
    - websockets>=11.0.0
    # Development tools
    - black>=23.0.0
    - isort>=5.12.0
    - flake8>=6.0.0 